### ISSUE TITLE
control levels of government returned as query parameters

### ISSUE THREAD

**Issue by derekeder** [datamade/my-reps#14]
From @ghing in #13:

> I see that you can configure levels in `js/lookup_tools.js`, but it would be better to read these from URL query parameters. That way, someone could iframe in the search and just change the iframe URL to specify different levels of government.

What pattern is easiest?

* `/?show_federal=1&show_state=1&show_county=1&show_local=1`
* `/?results_level=fed,state,county,local`

**Comment by ghing** [comment]
Another option:

* `/?results_level=fed&results_level=state&results_level=county`

I'd say use whichever format makes the parsing code in the JavaScript easiest, smallest.

My gut feeling is that it's `/?results_level=fed,state,county,local`.  

[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) would make this easy, but it has limited browser support.

**Comment by derekeder** [comment]
Yup we should be able to pull those params either way. I'll go ahead and start a PR

**Comment by derekeder** [comment]
@ghing finally got around to this. I ended up adding checkboxes below the search box that lets you select the level of government you want returned. This is also saved in the URL.

Here's an example: http://myreps.datamade.us/#/?address=1515%20W%20Augusta%20Blvd%2C%20Chicago%2C%20IL%2C%20United%20States&results_level=local&results_level=county

<img width="776" alt="screen shot 2017-05-30 at 5 30 34 pm" src="https://cloud.githubusercontent.com/assets/919583/26607762/b72724d0-455d-11e7-9232-e3a7e3728b14.png">
