### ISSUE TITLE
precursors to enabling jekyll

### ISSUE THREAD

**Issue by mroswell** [datamade/my-reps#5]
To install, I had to do the following:

```
$ brew update
$ brew upgrade rbenv ruby-build
$ source ~/.rvm/scripts/rvm
$ rvm install ruby-2.2.4
$ gem install jekyll
$ gem install jekyll-redirect-from
$ jekyll serve -w
```

Maybe I didn't need all that, but that's what worked for me, after getting these messages:

```
$ jekyll serve -w
-bash: jekyll: command not found
```

```
$ gem install jekyll
rbenv: version `ruby-2.2.4' is not installed
```

**Comment by derekeder** [comment]
Thanks for pointing this out @mroswell. 

Depending on the operating system the install instructions for jekyll will differ. In https://github.com/datamade/my-reps/commit/570a0c5da74a73b64f977b9196550293634668c3, I added a link to jekyll's installation instructions, which addresses this.
