### ISSUE TITLE
County capitalization

### ISSUE THREAD

**Issue by mroswell** [datamade/my-reps#6]
Capitalize "Baltimore City" (not "Baltimore city")
Sample address: 1000 N. Charles Street, Baltimore, MD 

(BTW, Baltimore City is a separate jurisdiction from Baltimore County. So far I have found the latter properly capitalized.)

**Comment by derekeder** [comment]
thanks @mroswell! Please report this to Google. I've added instructions on how to: http://myreps.datamade.us/about.html#report-data
