### ISSUE TITLE
Authentication popup on Mobile

### ISSUE THREAD

**Issue by aok-solutions** [datamade/my-reps#9]
When accessing the app on mobile, once you type in an address and click search an authentication popup comes up (see attached). You can click cancel to ignore it, and everything will still work fine, but it's a bit of a jarring/confusing user experience. 

![img_9429](https://cloud.githubusercontent.com/assets/6664458/17179435/d77daeb4-53de-11e6-927e-a16a220e421b.PNG)

**Comment by derekeder** [comment]
@aok-solutions I just tried the same search but did not get this message. 

http://myreps.datamade.us/#/?address=Aon%20Center%2C%20East%20Randolph%20Street%2C%20Chicago%2C%20IL%2C%20United%20States

I believe this is coming from the network you're on (illinois.gov?), not our website.

**Comment by aok-solutions** [comment]
Tested it on multiple networks, same problem. Must just be my phone because I tried it with other phones and didn't see it come up. Not sure what the cause is.
